# Generated by Django 5.0.14 on 2026-01-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice Mode"),
                            ("timed", "Timed Quiz"),
                            ("custom", "Custom Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True, help_text="Total time limit in seconds", null=True
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("total_score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=0)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Session",
                "verbose_name_plural": "Quiz Sessions",
                "db_table": "quiz_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "time_allocated",
                    models.IntegerField(
                        blank=True,
                        help_text="Time allocated for this question in seconds",
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "quiz_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="quizzes.quizsession",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["quiz_session", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(
                fields=["student", "is_completed"],
                name="quiz_sessio_student_162b06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(
                fields=["created_at"], name="quiz_sessio_created_1312f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together={("quiz_session", "question")},
        ),
    ]
