# Generated by Django 5.0.14 on 2026-01-11 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("quizzes", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("grade", models.IntegerField(help_text="Kelas (1-6)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        default=30, help_text="Waktu pengerjaan dalam menit"
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70, help_text="Nilai minimal kelulusan (0-100)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="quiz_session",
        ),
        migrations.AlterModelOptions(
            name="quizsession",
            options={"ordering": ["-started_at"]},
        ),
        migrations.RemoveIndex(
            model_name="quizsession",
            name="quiz_sessio_student_162b06_idx",
        ),
        migrations.RemoveIndex(
            model_name="quizsession",
            name="quiz_sessio_created_1312f2_idx",
        ),
        migrations.RenameField(
            model_name="quizsession",
            old_name="due_date",
            new_name="completed_at",
        ),
        migrations.RenameField(
            model_name="quizsession",
            old_name="is_completed",
            new_name="passed",
        ),
        migrations.RenameField(
            model_name="quizsession",
            old_name="created_at",
            new_name="started_at",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="quiz_type",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="time_limit",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="title",
        ),
        migrations.RemoveField(
            model_name="quizsession",
            name="total_score",
        ),
        migrations.AddField(
            model_name="quizsession",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name="quizsession",
            table=None,
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quizzes", to="questions.question"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subjects.subject"
            ),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="quizzes.quiz",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
