# Generated by Django 5.0.14 on 2026-01-13 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_alter_quizquestion_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AlterModelOptions(
            name="quizsession",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Quiz Session",
                "verbose_name_plural": "Quiz Sessions",
            },
        ),
        migrations.AddField(
            model_name="quizsession",
            name="grade",
            field=models.IntegerField(
                default=1,
                help_text="Kelas untuk filter mata pelajaran",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizsession",
            name="is_proxy_mode",
            field=models.BooleanField(
                default=False,
                help_text="True jika quiz dijalankan oleh parent atas nama student",
            ),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="proxy_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent yang menjalankan proxy quiz",
                limit_choices_to={"role": "parent"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proxy_quiz_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Proxy User",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="grade",
            field=models.IntegerField(
                help_text="Kelas (1-6)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quizsession",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(
                fields=["student", "completed_at"],
                name="quizzes_qui_student_fd3d11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(fields=["grade"], name="quizzes_qui_grade_8b4e10_idx"),
        ),
    ]
