# Generated by Django 5.0.14 on 2026-01-17 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("quizzes", "0003_architecture_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question_count",
            field=models.IntegerField(
                blank=True,
                help_text="Only for Subject Quiz: number of random questions to generate",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("subject_based", "Subject Quiz (Random)"),
                    ("custom", "Custom Quiz"),
                ],
                default="custom",
                help_text="Type of quiz: Subject (random questions) or Custom (specific questions)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only for Custom Quiz: manually select questions",
                related_name="quizzes",
                to="questions.question",
            ),
        ),
    ]
