# Generated by Django 5.0.14 on 2026-01-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("quizzes", "0004_add_quiz_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="session_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Questions actually used in this quiz session",
                related_name="quiz_sessions",
                to="questions.question",
            ),
        ),
    ]
