# Generated by Django 5.0.14 on 2026-01-17 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_add_session_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="question_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of random questions to use per quiz session",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
