# Generated by Django 6.0.5 on 2026-06-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('quizzes', '0006_update_quiz_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.grade'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='grade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.grade'),
        ),
    ]
