# Generated by Django 5.0.14 on 2026-01-13 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by_parent",
                    models.BooleanField(
                        default=False,
                        help_text="True if parent created the student account",
                        verbose_name="Created by Parent",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Parent's notes about this student",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Student Link",
                "verbose_name_plural": "Parent-Student Links",
                "db_table": "parent_students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Only for students",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                blank=True,
                help_text="Only for students: Grade level (1-6)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Grade/Kelas",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["grade"], name="users_grade_871f3e_idx"),
        ),
        migrations.AddField(
            model_name="parentstudent",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to={"role": "parent"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="parentstudent",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudent",
            index=models.Index(
                fields=["parent", "status"], name="parent_stud_parent__42cfd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudent",
            index=models.Index(
                fields=["student", "status"], name="parent_stud_student_e89154_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parentstudent",
            unique_together={("parent", "student")},
        ),
    ]
