# Generated by Django 6.0.5 on 2026-06-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0002_architecture_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_ref',
            field=models.ForeignKey(blank=True, help_text='New grade reference (replaces integer grade).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic.grade'),
        ),
    ]
