# Generated by Django 6.0.5 on 2026-06-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_grade_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('parent', 'Parent'), ('student', 'Student'), ('tutor', 'Tutor')], default='student', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Family Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_student_links', to='accounts.family'),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_prefs', models.JSONField(blank=True, default=dict)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone (secondary)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
                'db_table': 'tutor_profiles',
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_family', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('tutor', 'Tutor')], max_length=20, verbose_name='Role in Family')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Membership',
                'verbose_name_plural': 'Family Memberships',
                'db_table': 'family_memberships',
                'ordering': ['family', 'role_in_family'],
                'unique_together': {('family', 'user')},
            },
        ),
    ]
