# Generated by Django 5.0.14 on 2026-01-13 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["grade", "name"],
                "verbose_name": "Student (Deprecated)",
                "verbose_name_plural": "Students (Deprecated)",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the new User model (for migration)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="pengajar",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "parent"},
                related_name="old_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
