# Generated by Django 5.0.14 on 2026-01-11 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KompetensiDasar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "grade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kompetensi",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kompetensi Dasar",
                "verbose_name_plural": "Kompetensi Dasar",
                "db_table": "kompetensi_dasar",
                "ordering": ["grade", "subject", "code"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("skill", "Skill"),
                            ("topic", "Topic"),
                            ("difficulty", "Difficulty"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["category"], name="tags_categor_73c8b8_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("pilgan", "Pilihan Ganda"),
                            ("essay", "Essay"),
                            ("isian", "Isian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("mudah", "Mudah"),
                            ("sedang", "Sedang"),
                            ("sulit", "Sulit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("answer_key", models.TextField(verbose_name="Answer Key")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
                ("has_image", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="questions/images/"
                    ),
                ),
                ("has_math", models.BooleanField(default=False)),
                (
                    "estimated_time",
                    models.IntegerField(default=60, help_text="In seconds"),
                ),
                ("points", models.IntegerField(default=10)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kompetensi_dasar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions",
                        to="questions.kompetensidasar",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="subjects.topic",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="questions", to="questions.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
                "ordering": ["topic", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="kompetensidasar",
            index=models.Index(
                fields=["grade", "subject"], name="kompetensi__grade_45561f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kompetensidasar",
            unique_together={("code", "subject", "grade")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["topic", "difficulty"], name="questions_topic_i_f35e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="questions_questio_8af709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_at"], name="questions_created_2d11fa_idx"
            ),
        ),
    ]
