# Generated by Django 5.0.14 on 2026-01-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("quizzes", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_given", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("time_taken", models.IntegerField(help_text="Time taken in seconds")),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="questions.question",
                    ),
                ),
                (
                    "quiz_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quizsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
                "db_table": "attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "created_at"],
                        name="attempts_student_05bd54_idx",
                    ),
                    models.Index(
                        fields=["student", "question"],
                        name="attempts_student_c06e9d_idx",
                    ),
                    models.Index(
                        fields=["quiz_session"], name="attempts_quiz_se_f55859_idx"
                    ),
                    models.Index(
                        fields=["is_correct"], name="attempts_is_corr_283888_idx"
                    ),
                ],
            },
        ),
    ]
