# Generated by Django 5.0.14 on 2026-01-13 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("quizzes", "0003_architecture_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="answer_given",
            field=models.TextField(verbose_name="Answer Given"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="is_correct",
            field=models.BooleanField(verbose_name="Is Correct"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="points_earned",
            field=models.IntegerField(default=0, verbose_name="Points Earned"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="quiz_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="quizzes.quizsession",
                verbose_name="Quiz Session",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="time_taken",
            field=models.IntegerField(
                help_text="Time taken in seconds", verbose_name="Time Taken"
            ),
        ),
    ]
