# Generated by Django 5.0.14 on 2026-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_architecture_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="answer_given",
            field=models.TextField(blank=True, default="", verbose_name="Answer Given"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Is Correct"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="time_taken",
            field=models.IntegerField(
                default=0, help_text="Time taken in seconds", verbose_name="Time Taken"
            ),
        ),
    ]
